[package]
name = "hrm"
version = "0.1.0"
authors = ["Niko Lepka <slench102+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
